routes/web.php
<?php


//rutas del front

//rutas de prueba
//Route::get('/calendario','PruebaController@calendario');
//Route::get('/graficoExcel','PruebaController@graficoExcel');
//Route::get('/exportarPdf','PruebaController@exportarPdf');
//Route::get('/subirExcelVenta','PruebaController@importarExcelVenta');
//Route::get('/subirExcelAtencion','PruebaController@importarExcelVenta');

//Route::get('/login', function () {
  //  return redirect('/');
//});
Route::get('/','front\PanelController@index');
Route::post('/iniciarSession', 'front\PanelController@iniciarSession');
Route::match(['get','post'],'/iniciarSesionAdmin', 'LoginController@iniciarSesionAdmin');
Route::get('/cerrarSesion', 'LoginController@cerrarSesion');

//Route::get('/olvido','back\UsuarioController@olvido');

Route::middleware(['ident'])->group(function () 
{
	//rutas del back
	Route::get('/panel','back\PanelController@index');
	Route::get('/semestre','back\SemestreController@index');
	Route::match(['get','post'],'/semestre/registrar','back\SemestreController@registrar');
	Route::match(['get','post'],'/semestre/{id_semestre}/editar','back\SemestreController@editar');

	//rutas para escuela
	Route::get('/escuela','back\EscuelaController@index');
	Route::post('/escuela/insertar','back\EscuelaController@insertar');
	Route::post('/escuela/{id_escuela}/actualizar','back\EscuelaController@actualizar');

	//rutas para servicio
	Route::get('/servicio','back\ServicioController@index');
	Route::post('/servicio/insertar','back\ServicioController@insertar');
	Route::post('/servicio/{id_escuela}/actualizar','back\ServicioController@actualizar');

	//rutas para usuario
	Route::get('/usuario','back\UsuarioController@index')->name('usuario.index')->middleware('permiso:usuario.index');
	Route::post('/usuario/insertar','back\UsuarioController@insertar')->name('usuario.registrar')->middleware('permiso:usuario.registrar');
	Route::post('/usuario/{id_escuela}/actualizar','back\UsuarioController@actualizar')->name('usuario.editar')->middleware('permiso:usuario.editar');;


	//rutas para cambiar de contraseña
	Route::match(['get','post'],'/cambiarPassword','back\UsuarioController@cambiarPassword');
	//Route::get('/consumo','PruebaController@index');
	//rutas para estudiante
	Route::get('/estudiante','back\EstudianteController@index');
	Route::post('/estudiante/insertar','back\EstudianteController@insertar');
	Route::get('/estudiante/{dni}/buscar','back\EstudianteController@buscar');
	Route::post('/estudiante/{codigo}/actualizar','back\EstudianteController@actualizar');
	Route::match(['get','post'],'/estudiante/registroMasivo','back\EstudianteController@registroMasivo');
	Route::get('/estudiante/exportarExcel','back\EstudianteController@exportarExcel');
	Route::get('estudiante/{dni}/ficha','back\EstudianteController@fichaPdf');
	Route::get('estudiante/{dni}/historial','back\EstudianteController@historialPdf');


	//rutas para beneficiario
	Route::get('/beneficiario','back\BeneficiarioController@index');
	Route::get('/beneficiario/escuela/{id}','back\BeneficiarioController@listaEscuela');
	Route::get('/beneficiario/estudiante/buscar','back\BeneficiarioController@buscarEstudiante');
	Route::post('/beneficiario/insertar','back\BeneficiarioController@insertar');
	Route::post('/beneficiario/eliminar','back\BeneficiarioController@eliminar');
	Route::post('/beneficiario/cambiarTipo','back\BeneficiarioController@cambiarTipo');
	Route::post('/beneficiario/{id_beneficiario}/actualizar','back\BeneficiarioController@actualizar');
	Route::post('/beneficiario/{id_beneficiario}/suspender','back\BeneficiarioController@suspender');
	Route::get('/beneficiario/escuela/{id_escuela}/listaPdf','back\BeneficiarioController@listaBeneficiariosPdf');
	Route::get('/beneficiario/escuela/{id_escuela}/listaVentaPdf','back\BeneficiarioController@listaVentaPdf');
	

	//rutas cupo programado
	Route::get('/cupoprogramado','back\CupoProgramadoController@index');
	Route::post('/cupoprogramado/insertar','back\CupoProgramadoController@insertar');
	Route::post('/cupoprogramado/actualizar','back\CupoProgramadoController@actualizar');

	//rutas periodo de atencion
	Route::get('/periodoAtencion','back\PeriodoAtencionController@index');
	Route::post('/periodoAtencion/insertar','back\PeriodoAtencionController@insertar');
	Route::post('/periodoAtencion/{id_periodoAtencion}/actualizar','back\PeriodoAtencionController@actualizar');
	Route::post('/periodoAtencion/cambiarEstado','back\PeriodoAtencionController@cambiarEstado');

	//rutas para venta de cupos
	Route::get('/ventaCupo','back\VentaController@index');
	Route::match(['get','post'],'/ventaCupo/registrarVentaRegular','back\VentaController@registrarVentaRegular')->name('ventaRegular');
	Route::match(['get','post'],'/ventaCupo/registrarVentaLibre','back\VentaController@registrarVentaLibre')->name('ventaLibre');

	Route::match(['get','post'],'/ventaCupo/reporteVenta','back\ReporteVentaController@index')->name('reporteVenta');
	Route::match(['get','post'],'ventaCupo/resumenVentaPdf','back\ReporteVentaController@resumenVentaPdf');
	Route::match(['get','post'],'ventaCupo/resumenVentaExcel','back\ReporteVentaController@resumenVentaExcel');
	Route::get('/ventaCupo/rptListaVentaPdf','back\ReporteVentaController@rptListaVentaPdf');

	//rutas para atencion de comensales
	Route::get('/atencion','back\AtencionController@index');
	Route::match(['get','post'],'/atencion/registrarAtencionRegular','back\AtencionController@registrarAtencionRegular')->name('atencionRegular');
	Route::match(['get','post'],'/atencion/registrarAtencionLibre','back\AtencionController@registrarAtencionLibre')->name('atencionLibre');
	Route::match(['get','post'],'/atencion/reporteAtencion','back\ReporteAtencionController@index')->name('reporteAtencion');

	Route::match(['get','post'],'/atencion/rptAtencionExcel','back\ReporteAtencionController@rptAtencionExcel');
	Route::match(['get','post'],'/atencion/rptAtencionPdf','back\ReporteAtencionController@rptAtencionPdf');

	//rutas para roles de usuario
	Route::get('/rol','back\RolController@index');
	Route::match(['get','post'],'/rol/registrar','back\RolController@registrar');
	Route::match(['get','post'],'/rol/{id_rol}/editar','back\RolController@editar');


	//Route::get('/excelestudiantes','PruebaController@exportarExcel');
	Route::get('/subirExcel','PruebaController@importarExcel');
	Route::post('/subirExcel','PruebaController@procesarExcel');
	//Route::match(['get','post'],'/subirFoto','PruebaController@subirFoto');

	//Rutas de ficha back
	Route::get('ficha/','back\FichaController@index');
	Route::get('ficha/reporteProcedencia','back\FichaController@reporteProcedencia');
	Route::get('ficha/reporteModalidadIngreso','back\FichaController@reporteModalidadIngreso');
	Route::get('ficha/reporteEdadPromedio','back\FichaController@reporteEdadPromedio');

});

//rutas del front
Route::middleware(['estudiante'])->group(function () 
{
	Route::get('fichaEstudiante/','front\PanelController@ficha');
	Route::post('fichaEstudiante/tab1','front\PanelController@fichaTab1');
	Route::post('fichaEstudiante/tab2','front\PanelController@fichaTab2');
	Route::post('fichaEstudiante/tab3','front\PanelController@fichaTab3');
	Route::post('fichaEstudiante/tab4','front\PanelController@fichaTab4');
	Route::post('fichaEstudiante/tab5','front\PanelController@fichaTab5');
	Route::get('fichaEstudiante/pdf','front\PanelController@fichaPdf');

	Route::get('fichaEstudiante/listProvincias/{id_departamento}','front\PanelController@listProvincias');
	Route::get('fichaEstudiante/listDistritos/{id_provincia}','front\PanelController@listDistritos');
});

app/Http/Controllers/PruebaController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Model\Estudiante;
use App\Model\Escuela;
use Session;
//use Excel;
use DB;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Contracts\Routing\ResponseFactory as Response;
use Crabbly\FPDF\FPDF;

class PruebaController extends Controller
{
    public function index()
    {   
        $escuelas=Escuela::withCount('estudiantes')->where('grupo','A')->get();
        return view('consumo',compact('escuelas')); 
    }
    public function procesar( Request $request){
    	/*if (Request::isMethod('get')) {
            return redirect->route('/');
        }*/
        $this->validate($request,['codigo'=>'required|digits_between:6,10']);//validamos los datos
		$codigo=trim($request->get('codigo'));
        if (strlen($codigo)===8) {
             $estudiante=Estudiante::whereRaw('dni=? ',[$codigo])->first();//consulta a la BD    
        }
        else{
            $codigo=substr($codigo,-6);
            $estudiante=Estudiante::whereRaw('codigo=? ',[$codigo])->first();//consulta a la BD    
        }
        $escuelas=Escuela::withCount('estudiantes')->where('grupo','A')->get();  
        if ($estudiante) {
            return view('consumo',compact('estudiante','escuelas'));    
        }
        $request->session()->flash('msj-warning', 'El alumno no se encuentra en la lista ');
        return redirect()->back();	    	
    }

    public function exportarExcel()
    {   
        $estudiantes=Estudiante::All();
         $datos;//arreglo de arreglos
         $i=1;
           foreach ($estudiantes as $estudiante) {
            $i++;
                $datos[]=[$estudiante->codigo, $estudiante->dni,$estudiante->nombre,$estudiante->apellido,$estudiante->escuela_id];
            }
        Excel::create('Lista de estudiantes', function($excel) use($datos,$i)
        {
            $excel->sheet('Hoja 1', function($sheet) use($datos,$i)
            {
                $sheet->setOrientation('landscape');
                //$sheet->mergeCells('A1:E1');
                $sheet->setAutoSize(true);
                //$sheet->setHeight(1,50);

                $sheet->cells('A1:E1',function($cells){
                    $cells->setAlignment('center');
                    $cells->setValignment('center');
                    //$cells->setBackground('#1497cc');
                    $cells->setBackground('#2467BA');
                    $cells->setFontColor('#ffffff');
                    $cells->setFontSize(12);
                   
                });

                $sheet->setBorder('A2:E'.$i, 'thin');//borde de todo
                $sheet->cell('A1', function($cell){$cell->setValue('CODIGO');});
                $sheet->cell('B1', function($cell){$cell->setValue('DNI');});
                $sheet->cell('C1', function($cell){$cell->setValue('NOMBRE');});
                $sheet->cell('D1', function($cell){$cell->setValue('APELLIDO');});
                $sheet->cell('E1', function($cell){$cell->setValue('ESCUELA_ID');});   

               $sheet->fromArray($datos,null,'A2',false,false);//aqui se forma la matriz con los datos

                          
            });
        })->export('xls');
        
        
    }
    public function calendario()
    {
          Excel::create('calendario', function($excel) {

            $excel->sheet('mes1', function($sheet) {

                $fechas=DB::select('SELECT DISTINCT DATE_FORMAT(fecha, "%d-%m-%Y") AS dia FROM atencion WHERE id_periodoatencion=?',[1]);
         
            $comensales= DB::table('venta_cupo')
                    ->join('estudiante', 'venta_cupo.dni_estudiante', '=', 'estudiante.dni_estudiante')
                    ->join('periodo_atencion', 'venta_cupo.id_periodoatencion', '=', 'periodo_atencion.id_periodoatencion')
                    ->where('periodo_atencion.id_periodoatencion',1)->where('venta_cupo.id_servicio',2)->where('estudiante.id_escuela',1)
                    ->select('venta_cupo.*', 'estudiante.nombres','estudiante.apellidos','estudiante.dni_estudiante')->orderBy('tipo_venta','DESC')
                    ->get();
            
            //convertimos la coleccion en array       
            $comensales=$comensales->toArray();
            
           if (count($comensales)>0) {
                //asignamos las columnas deasistencia por cada fecha
                for ($i=0;  $i <count($comensales) ; $i++) {
                    //convertimos el objeto en array
                    $datos[$i]=(array) $comensales[$i];
                    //generamos una columna por cada dia atendido y buscamos la asistencia
                    foreach ($fechas as $fecha){
                        $datos[$i]=array_add($datos[$i], $fecha->dia, buscar_asistencia($comensales[$i]->id_servicio,$comensales[$i]->dni_estudiante,$comensales[$i]->id_periodoatencion,$fecha->dia));
                    }
                    
                }
                
                $comensales=$datos;

                $sheet->loadView('calendario',compact('comensales','fechas') );
             }   

            });

        })->export('xls');

    }
   public function graficoExcel()
    {
        $excel = new \PHPExcel();

        $excel->createSheet();
        $excel->setActiveSheetIndex(1);
        $excel->getActiveSheet()->setTitle('ChartTest');

        $objWorksheet = $excel->getActiveSheet();
        $objWorksheet->fromArray(
                array(
                    array('', 'Rainfall (mm)', 'Temperature (°F)', 'Humidity (%)'),
                    array('Jan', 78, 52, 61),
                    array('Feb', 64, 54, 62),
                    array('Mar', 62, 57, 63),
                    array('Apr', 21, 62, 59),
                    array('May', 11, 75, 60),
                    array('Jun', 1, 75, 57),
                    array('Jul', 1, 79, 56),
                    array('Aug', 1, 79, 59),
                    array('Sep', 10, 75, 60),
                    array('Oct', 40, 68, 63),
                    array('Nov', 69, 62, 64),
                    array('Dec', 89, 57, 66),
                )
        );

        $dataseriesLabels1 = array(
            new \PHPExcel_Chart_DataSeriesValues('String', 'Grafico!$B$1', NULL, 1), //  Temperature
        );
        $dataseriesLabels2 = array(
            new \PHPExcel_Chart_DataSeriesValues('String', 'Grafico!$C$1', NULL, 1), //  Rainfall
        );
        $dataseriesLabels3 = array(
            new \PHPExcel_Chart_DataSeriesValues('String', 'Grafico!$D$1', NULL, 1), //  Humidity
        );

        $xAxisTickValues = array(
            new \PHPExcel_Chart_DataSeriesValues('String', 'Grafico!$A$2:$A$13', NULL, 12), //  Jan to Dec
        );

        $dataSeriesValues1 = array(
            new \PHPExcel_Chart_DataSeriesValues('Number', 'Grafico!$B$2:$B$13', NULL, 12),
        );

        //  Build the dataseries
        $series1 = new \PHPExcel_Chart_DataSeries(
                \PHPExcel_Chart_DataSeries::TYPE_BARCHART, // plotType
                \PHPExcel_Chart_DataSeries::GROUPING_CLUSTERED, // plotGrouping
                range(0, count($dataSeriesValues1) - 1), // plotOrder
                $dataseriesLabels1, // plotLabel
                $xAxisTickValues, // plotCategory
                $dataSeriesValues1                              // plotValues
        );
        //  Set additional dataseries parameters
        //      Make it a vertical column rather than a horizontal bar graph
        $series1->setPlotDirection(\PHPExcel_Chart_DataSeries::DIRECTION_COL);

        $dataSeriesValues2 = array(
            new \PHPExcel_Chart_DataSeriesValues('Number', 'Grafico!$C$2:$C$13', NULL, 12),
        );

        //  Build the dataseries
        $series2 = new \PHPExcel_Chart_DataSeries(
                \PHPExcel_Chart_DataSeries::TYPE_LINECHART, // plotType
                \PHPExcel_Chart_DataSeries::GROUPING_STANDARD, // plotGrouping
                range(0, count($dataSeriesValues2) - 1), // plotOrder
                $dataseriesLabels2, // plotLabel
                NULL, // plotCategory
                $dataSeriesValues2                              // plotValues
        );

        $dataSeriesValues3 = array(
            new \PHPExcel_Chart_DataSeriesValues('Number', 'Grafico!$D$2:$D$13', NULL, 12),
        );

        //  Build the dataseries
        $series3 = new \PHPExcel_Chart_DataSeries(
                \PHPExcel_Chart_DataSeries::TYPE_AREACHART, // plotType
                \PHPExcel_Chart_DataSeries::GROUPING_STANDARD, // plotGrouping
                range(0, count($dataSeriesValues2) - 1), // plotOrder
                $dataseriesLabels3, // plotLabel
                NULL, // plotCategory
                $dataSeriesValues3                              // plotValues
        );


        //  Set the series in the plot area
        $plotarea = new \PHPExcel_Chart_PlotArea(NULL, array($series1, $series2, $series3));
        $legend = new \PHPExcel_Chart_Legend(\PHPExcel_Chart_Legend::POSITION_RIGHT, NULL, false);
        $title = new \PHPExcel_Chart_Title('Grafica anhelada maternofetal :(');

        //  Create the chart
        $chart = new \PHPExcel_Chart(
                'chart1', // name
                $title, // title
                $legend, // legend
                $plotarea, // plotArea
                true, // plotVisibleOnly
                0, // displayBlanksAs
                NULL, // xAxisLabel
                NULL            // yAxisLabel
        );

        //  Set the position where the chart should appear in the worksheet
        $chart->setTopLeftPosition('F2');
        $chart->setBottomRightPosition('O16');

        //  Add the chart to the worksheet
        $objWorksheet->addChart($chart);

        $writer = new \PHPExcel_Writer_Excel2007($excel);
        $writer->setIncludeCharts(TRUE);

        // Save the file.
        $writer->save(public_path().'/file.xlsx');
    }
    public function importarExcel(){
        return view('subirExcel');

    }

resources/views/calendario.blade.php
<html>
<link href="{{asset('css/style.css')}}" >

<br>

<table class=" table table-sm table-hover table-bordered">
	<thead >
		<tr>
			<th>#</th> 
			<th>DNI</th> 
			<th>APELLIDOS Y NOMBRES</th>
			<th>TIPO VENTA</th>
			@foreach ($fechas as $fecha)
				<th width="5" class="m-0 p-0" ><p  class="texto-vertical-1 m-0 p-1 ">{{date("d/m", strtotime($fecha->dia))}}</p></th> 
			@endforeach
			<th></th>
			<th></th>
			<th>#</th> 
			<th>DNI</th> 
			<th>APELLIDOS Y NOMBRES</th>
			<th>TIPO VENTA</th>
			@foreach ($fechas as $fecha)
				<th width="5" class="m-0 p-0" ><p  class="texto-vertical-1 m-0 p-1 ">{{date("d/m", strtotime($fecha->dia))}}</p></th> 
			@endforeach
		</tr>
	</thead>
	<tbody>
			@php
				$i=1 ;
			@endphp
			@foreach ($comensales as $comensal)

			<tr>
				<td>{{$i++}}</td>
				<td >{{$comensal['dni_estudiante']}}</td>
				<td>{{$comensal['apellidos']}} {{$comensal['nombres']}}</td>
				<td> {{($comensal['tipo_venta']==1)? 'Regular':'Libre' }} </td>
				@foreach ($fechas as $fecha)
						
					<td >{{$comensal[$fecha->dia]}}</td> 
				@endforeach
				<td></td>
				<td></td>
			</tr>	
			@endforeach
			

			
		
	</tbody>
</table>

</html>

resources/views/consumo.blade.php
<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Document</title>
	    <link href="{{asset('css/app.css')}}" rel='stylesheet' type='text/css' />
	</head>
	<body>
	<br>
	<div class="container-fluid">	
		<div class="row">
			<div class="col-sm-6 col-sm-push-3 ">
				<div class="panel panel-primary">
					<div class="panel-heading text-center">	<strong>Registro de atención {{date('d-m-Y')}}</strong> </div>
						<div class="panel-body">
							<form action=" {{ url('/consumo')}}" method="POST" id="formulario" class="">
								{{csrf_field()}}
								<div class="input-group">
									<input type="text" name="codigo" class="form-control" placeholder="ingrese codigo..." maxlength="10" minlength="6" required="required" autofocus="autofocus">
									<span class="input-group-btn">
										<button class="btn btn-default"> Buscar</button>
									</span>
								</div>
							</form>
							<br>
							@if (@$estudiante)
								<label>Código universitario: </label> {{$estudiante->codigo }}<br>
								<label>Dni:  </label> {{$estudiante->dni }}<br>
								<label>Nombres: </label> {{$estudiante->nombre }}<br>
								<label>Apellidos: </label> {{$estudiante->apellido }}<br>
								
								<label>Carrera: </label> {{$estudiante->escuela->nombre }}<br>
								
							@endif
							
							@include('partials.mensajes')
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading"><strong>Resumen de atención</strong></div>
					<div class="panel-body">
						<table class="table table-bordered table-condensed table-striped">
							<thead>
								<tr>
								<th>Carrera</th>
								<th>Atendidos</th>
							</tr>	
							</thead>
							<tbody>
								@foreach ($escuelas as $escuela)
									<tr>
										<td>{{$escuela->nombre }}</td>
										<td>{{$escuela->estudiantes_count }}</td>
									</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>	
	</div>
	</body>
</html>	

resources/views/home.blade.php
@extends('layouts.coreui')
@section('breadcrumb')
    <li class="breadcrumb-item">Home</li>
      <li class="breadcrumb-item">
        <a href="#">Admin</a>
      </li>
      <li class="breadcrumb-item active">Dashboard</li>
      <!-- Breadcrumb Menu-->
      
@endsection

@section('content')

    <div class="row">
        <div class="col-md-8 offset-2 ">
            <div class="card  ">
                <div class="card-header ">Dashboard</div>

                <div class="card-body">
                    Bienvenido!
                </div>
            </div>
        </div>
    </div>

@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
        <br>
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    Bienvenido!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/subirFoto.blade.php
<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Document</title>
	    <link href="{{asset('css/app.css')}}" rel='stylesheet' type='text/css' />
	</head>
	<body>
	<br>
	<div class="container-fluid">	
		<div class="row">
			<div class="col-sm-6 col-sm-push-3 ">
				<div class="panel panel-primary">
					<div class="panel-heading text-center">	<strong>Registro de atención {{date('d-m-Y')}}</strong> </div>
						<div class="panel-body">
							<form action=" {{ url('/subirFoto')}}" method="POST" id="formulario" class="" enctype="multipart/form-data">
								{{csrf_field()}}
								<div class="input-group">
									<input type="file" name="archivo" class="form-control"   required="required" >
									<span class="input-group-btn">
										<button class="btn btn-primary"> Subir foto</button>
									</span>
								</div>
							</form>
							<br>
							
							
							@include('partials.mensajes')
					</div>
				</div>
				<div class="panel-body">
					<h3>fotos</h3>
					<img src="{{ asset('archivos/fotos/baka_cole.jpg') }}" alt="">
				</div>
				
			</div>
		</div>	
	</div>
	</body>
</html>	

resources/views/subirexcel.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Subir excel</title>
</head>
<body>
<center>
	@include('parcial.mensajes');
	<h2>Registar Estudiantes desde Excel</h2>
		<form action="{{ url('subirExcel') }}" method="POST" enctype="multipart/form-data">
			{{ csrf_field() }}
			<label><strong>Seleccione archivo Excel</strong></label><br>
			<input type="file" name="archivo"><br><br>
			<button>Subir Excel</button>
		</form>
</center>
	
</body>
</html>